[alerts]
# Path to alert rules
# FiXME don't commit this path
path = "/home/jimfitz/code/github.com/bf2fc6cc711aee1a0c2a/observability-resources-mk/resources/prometheus"
# Directories to exclude from search
exclude_dir = ["pod_monitors", "unit_tests"]
# File names to exclude from search
exclude_files = ["prometheus-rules-developer.yaml"]
# Severity level of alerts to look for tests against
severity = ["critical", "warning"]

[test]
# Path to the test files
# FiXME don't commit this path
path = "/home/jimfitz/code/github.com/bf2fc6cc711aee1a0c2a/observability-resources-mk/resources/prometheus/unit_tests"
exclude_dir = []

[script]
# Will cause the script to exit with value of one when a untested alert has a severity level in the fail_levels
fail_levels = ["critical"]